### Pair Programming Numpy I

1. Cread tres arrays: de una, dos y tres dimensiones.

    Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas en algunos casos. El array de 2 dimensiones debe ser de 2 filas y 3 columnas. El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [29]:
# Lo primero, importamos la librería:

import numpy as np

In [30]:
# Creamos los arrays según especificado:

array1 = np.random.randint((2, 3))
array2 = np.random.rand(3, 2)
array3 = np.random.random_sample((2, 3, 5))

In [31]:
# Comprobamos que las dimensiones son correctas:

print('Las dimensiones del array1 son', array1.ndim)
print('Las dimensiones del array2 son', array2.ndim)
print('Las dimensiones del array3 son', array3.ndim)

Las dimensiones del array1 son 1
Las dimensiones del array2 son 2
Las dimensiones del array3 son 3


In [32]:
# Chequead las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos
# devuelva las propiedades de una array que le pasemos.

2. Chequead las las propiedades básicas de cada array que os hayáis creado.

    Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [33]:
# Creamos una función para acceder a ellas rápidamente:

def propiedades(nuestro_array):
    print(f'La forma de nuestro array es', nuestro_array.shape)
    print(f'El tamaño de nuestro array es', nuestro_array.size)
    print(f'La dimensión de nuestro array es', nuestro_array.ndim)
    print(f'El tipo de nuestro array es', nuestro_array.dtype)

In [34]:
propiedades(array3)

La forma de nuestro array es (2, 3, 5)
El tamaño de nuestro array es 30
La dimensión de nuestro array es 3
El tipo de nuestro array es float64


In [35]:
propiedades(array2)

La forma de nuestro array es (3, 2)
El tamaño de nuestro array es 6
La dimensión de nuestro array es 2
El tipo de nuestro array es float64


In [36]:
propiedades(array1)

La forma de nuestro array es (2,)
El tamaño de nuestro array es 2
La dimensión de nuestro array es 1
El tipo de nuestro array es int64


3. Crear una matriz identidad de dos dimensiones de 3 filas y 3 columnas.

In [37]:
array4 = np.identity(3)

In [38]:
# Printeamos el array para visualizarlo:

array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
# Comprobamos sus propiedades:

propiedades(array4)

La forma de nuestro array es (3, 3)
El tamaño de nuestro array es 9
La dimensión de nuestro array es 2
El tipo de nuestro array es float64


3. Cread una matriz de tres dimensiones de unos.

    Igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [40]:
array5 = np.empty_like(array3)
array5

array([[[0.1870011 , 0.69469713, 0.30342266, 0.10086317, 0.22851845],
        [0.03711153, 0.542974  , 0.21811546, 0.41495   , 0.73498137],
        [0.97924597, 0.33562436, 0.42347401, 0.739043  , 0.12434873]],

       [[0.05027127, 0.02765239, 0.11226168, 0.22743971, 0.41741997],
        [0.69271548, 0.89973294, 0.28001352, 0.15916125, 0.30037465],
        [0.88503247, 0.03758266, 0.07171951, 0.8808234 , 0.36035452]]])

In [41]:
# Comprobamos las propiedades de nuestro array:

propiedades(array3)

La forma de nuestro array es (2, 3, 5)
El tamaño de nuestro array es 30
La dimensión de nuestro array es 3
El tipo de nuestro array es float64


4. Es el momento de hacer algunas operaciones entre arrays

    ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

In [43]:
np.add(array2, array4)

ValueError: operands could not be broadcast together with shapes (3,2) (3,3) 

In [ ]:
print('No se puede porque tienen formas distintas.')

No se puede porque tienen formas distintas.


In [44]:
# Lo demostramos comprobando sus propiedades:

propiedades(array2)

La forma de nuestro array es (3, 2)
El tamaño de nuestro array es 6
La dimensión de nuestro array es 2
El tipo de nuestro array es float64


In [45]:
propiedades(array4)

La forma de nuestro array es (3, 3)
El tamaño de nuestro array es 9
La dimensión de nuestro array es 2
El tipo de nuestro array es float64


In [46]:
print("El primer array tiene un tamaño de 6 y el segundo de 9")

El primer array tiene un tamaño de 6 y el segundo de 9


En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra.

In [47]:


# Creamos un array nuevo:

array5 = np.empty_like(array2)

In [48]:
array5

array([[0.35455657, 0.04486319],
       [0.19961465, 0.35972282],
       [0.01931873, 0.9110972 ]])

In [49]:
np.add(array2, array5)
(array2 + array5)

array([[1.14107723, 0.37805176],
       [0.66863794, 0.43169714],
       [0.80745542, 1.1985805 ]])

Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

In [50]:
np.multiply(array2, array5)
(array2 * array5)

array([[0.27886606, 0.0149479 ],
       [0.09362392, 0.0258908 ],
       [0.0152258 , 0.26192523]])

Dividid las dos matrices:

In [51]:
np.divide(array2, array5)
(array2 / array5)

array([[ 2.21832208,  7.42677017],
       [ 2.3496436 ,  0.20008272],
       [40.79649705,  0.31553527]])