### Pair Programming Numpy II

In [2]:
# Lo primero: importamos las librerías.

import  numpy as np
import pandas as pd

1. Cread un array de dos dimensiones de 5 filas y 3 columnas. 


In [3]:
bidimensional = np.random.rand (5,3)
bidimensional

array([[0.21480287, 0.67289624, 0.20656324],
       [0.32336784, 0.30578764, 0.45697484],
       [0.7823024 , 0.61097927, 0.21296122],
       [0.72079068, 0.80794059, 0.01144151],
       [0.91033859, 0.45065096, 0.89167763]])

Sobre el array creado anteriormente, extraed:
 - El valor de la primera fila y la segunda columna.

In [4]:
bidimensional[0,1]

0.6728962356192206


- Los valores de la segunda fila y las dos primeras columnas.

In [5]:
bidimensional [1,:2]

array([0.32336784, 0.30578764])


- Extraed las filas pares (incluyendo la 0) y todas las columnas.

In [6]:
bidimensional[::2,:]

array([[0.21480287, 0.67289624, 0.20656324],
       [0.7823024 , 0.61097927, 0.21296122],
       [0.91033859, 0.45065096, 0.89167763]])


- Extraed los valores que sean mayores que 0.5.

In [7]:
bidimensional[bidimensional>0.5]

array([0.67289624, 0.7823024 , 0.61097927, 0.72079068, 0.80794059,
       0.91033859, 0.89167763])


- Extraed los valores menores que 0.2 o mayores que 0.5

In [8]:
bidimensional [(bidimensional<0.2)|(bidimensional>0.5)]

array([0.67289624, 0.7823024 , 0.61097927, 0.72079068, 0.80794059,
       0.01144151, 0.91033859, 0.89167763])

2. Cread dos arrays de tres dimensiones:
- El primero de 2 matrices, 5 finales y 3 columnas.
- El segundo de 3 matrices, 2 filas y 5 columnas.

In [10]:
array1 = np.random.rand(2,5,3)
array2 = np.random.rand (3,2,5)

In [11]:
array1

array([[[0.01656644, 0.85194266, 0.7849455 ],
        [0.7781215 , 0.97485507, 0.69105209],
        [0.94847179, 0.16045113, 0.39397175],
        [0.64105929, 0.49325065, 0.08708293],
        [0.21213305, 0.96361207, 0.16961332]],

       [[0.23931295, 0.42889606, 0.45607471],
        [0.28651911, 0.852748  , 0.3997521 ],
        [0.16849063, 0.87434689, 0.94042724],
        [0.35774075, 0.30123913, 0.98485311],
        [0.72585076, 0.71568855, 0.89598957]]])

In [12]:
array2

array([[[0.15048806, 0.20599245, 0.33715315, 0.82377102, 0.11095997],
        [0.47015386, 0.06810613, 0.14201011, 0.52174916, 0.98970043]],

       [[0.87238611, 0.75315655, 0.09140296, 0.24151833, 0.56303923],
        [0.20995391, 0.01464653, 0.75055477, 0.69646203, 0.26522291]],

       [[0.55455573, 0.38987265, 0.53953379, 0.06168036, 0.23730326],
        [0.19451443, 0.51795996, 0.07125187, 0.59276397, 0.64674816]]])

- Haced un análisis exploratorio de los arrays creados.

In [13]:
# Acudimos a la función creada en el ejercicio anterior:

def propiedades(nuestro_array):
    print(f'La forma de nuestro array es', nuestro_array.shape)
    print(f'El tipo de nuestro array es', nuestro_array.dtype)
    print(f'El tamaño de nuestro array es', nuestro_array.size)
    print(f'Las dimensiones que tiene son', nuestro_array.ndim)

propiedades(array1)

La forma de nuestro array es (2, 5, 3)
El tipo de nuestro array es float64
El tamaño de nuestro array es 30
Las dimensiones que tiene son 3


In [14]:
propiedades (array2)

La forma de nuestro array es (3, 2, 5)
El tipo de nuestro array es float64
El tamaño de nuestro array es 30
Las dimensiones que tiene son 3


Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [15]:
array1 + array2

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

In [23]:
print("No se pueden sumar porque tienen formas diferentes.")

No se pueden sumar porque tienen formas diferentes.


In [18]:
array1

array([[[0.01656644, 0.85194266, 0.7849455 ],
        [0.7781215 , 0.97485507, 0.69105209],
        [0.94847179, 0.16045113, 0.39397175],
        [0.64105929, 0.49325065, 0.08708293],
        [0.21213305, 0.96361207, 0.16961332]],

       [[0.23931295, 0.42889606, 0.45607471],
        [0.28651911, 0.852748  , 0.3997521 ],
        [0.16849063, 0.87434689, 0.94042724],
        [0.35774075, 0.30123913, 0.98485311],
        [0.72585076, 0.71568855, 0.89598957]]])

In [19]:
array2

array([[[0.15048806, 0.20599245, 0.33715315, 0.82377102, 0.11095997],
        [0.47015386, 0.06810613, 0.14201011, 0.52174916, 0.98970043]],

       [[0.87238611, 0.75315655, 0.09140296, 0.24151833, 0.56303923],
        [0.20995391, 0.01464653, 0.75055477, 0.69646203, 0.26522291]],

       [[0.55455573, 0.38987265, 0.53953379, 0.06168036, 0.23730326],
        [0.19451443, 0.51795996, 0.07125187, 0.59276397, 0.64674816]]])

Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos: .reshape() .transpose()

Utiliza estas dos funciones para cambiar la forma de los array  y hacer operaciones entre ellos.

In [20]:
# Llamamos a los índices de cada array para utilizar los métodos:

array_traspo = np.transpose(array1,(1,2,0))

In [21]:
array_resha = np.reshape(array2, (5,3,2))

In [22]:
array_traspo + array_resha

array([[[0.1670545 , 0.44530541],
        [1.18909581, 1.25266707],
        [0.89590547, 0.92622857]],

       [[0.84622764, 0.42852922],
        [1.49660423, 1.84244842],
        [1.5634382 , 1.15290865]],

       [[1.03987475, 0.41000896],
        [0.72349036, 1.0843008 ],
        [0.40861828, 1.69098201]],

       [[1.33752132, 0.62296366],
        [1.04780638, 0.69111179],
        [0.62661672, 1.04653347]],

       [[0.44943631, 0.92036519],
        [1.48157204, 0.78694042],
        [0.7623773 , 1.54273772]]])