### Pair Programming Numpy IV 

In [3]:

# Lo primero, importamos la librería:

import numpy as np 

1. ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [4]:
# Usando el método random.seed():

np.random.seed(42)

arr1 = np.random.random_sample((2,5))
arr1

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258]])

In [5]:
np.random.seed(42)

arr2 = np.random.random_sample((2,4))
arr2

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615]])

2. Cread los siguientes arrays:
- Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

In [6]:
arr3 = np.random.randint(0,10,(2,3,5))
arr3

array([[[3, 7, 7, 2, 5],
        [4, 1, 7, 5, 1],
        [4, 0, 9, 5, 8]],

       [[0, 9, 2, 6, 3],
        [8, 2, 4, 2, 6],
        [4, 8, 6, 1, 3]]])

In [7]:
arr4 = np.random.randint(0,10,(2,3,5))
arr4

array([[[8, 1, 9, 8, 9],
        [4, 1, 3, 6, 7],
        [2, 0, 3, 1, 7]],

       [[3, 1, 5, 5, 9],
        [3, 5, 1, 9, 1],
        [9, 3, 7, 6, 8]]])

In [8]:
valores_unicos1 = np.unique(arr4)
valores_unicos1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [9]:
arr5 = np.random.binomial(10,0.3,size=(2,3,5))
arr5

array([[[6, 4, 4, 3, 3],
        [6, 3, 2, 2, 2],
        [0, 3, 3, 2, 0]],

       [[2, 4, 4, 3, 5],
        [4, 5, 5, 3, 1],
        [2, 4, 4, 3, 2]]])

In [10]:
valores_unicos2 = np.unique(arr5)
valores_unicos2

array([0, 1, 2, 3, 4, 5, 6])

3. En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:

- Elementos comunes entre los dos arrays

In [11]:

array_comun = np.intersect1d(valores_unicos1,valores_unicos2)
array_comun

print('Esto son los elementos comunes que tienen ambos arrays:', array_comun)

Esto son los elementos comunes que tienen ambos arrays: [0 1 2 3 4 5 6]


- Unión de los dos arrays.

In [12]:
array_union=np.union1d(valores_unicos1,valores_unicos2)
array_union

print('Esta es la unión de elementos de ambos arrays:', array_union)

Esta es la unión de elementos de ambos arrays: [0 1 2 3 4 5 6 7 8 9]



- ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial?

In [13]:
# ¿Qué elementos están en el array derivado de la distribución uniforme
#  y no en los únicos de la distribución binomial?
#  Extrae los valores númericos

elementos_uniformes = np.setdiff1d(valores_unicos1, valores_unicos2)

print('Estos son los elementos únicos de la distribución uniforme que no están en la distribución binomial:', elementos_uniformes)

Estos son los elementos únicos de la distribución uniforme que no están en la distribución binomial: [7 8 9]


4. Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

In [14]:
array1 = np.random.randint(1, 100, (80))
array2 = np.random.randint(1, 100, (80))

In [15]:
array1

array([35, 65, 99, 47, 78,  3,  1,  5, 90, 14, 27,  9, 79, 15, 90, 42, 77,
       51, 63, 96, 52, 96,  4, 94, 23, 15, 43, 29, 36, 13, 32, 71, 59, 86,
       28, 66, 42, 45, 62, 57,  6, 28, 28, 44, 84, 30, 62, 75, 92, 89, 62,
       97,  1, 27, 62, 77,  3, 70, 72, 27,  9, 62, 37, 97, 51, 44, 24, 79,
       59, 32, 96, 88, 52, 62, 58, 52, 12, 39,  2,  3])

In [16]:
array2

array([56, 81, 59,  2,  2, 92, 54, 87, 96, 97,  1, 19,  2, 53, 44, 90, 32,
       70, 32, 68, 55, 75, 56, 17, 38, 24, 69, 98, 70, 86, 11, 16, 97, 73,
       59, 70, 80, 93,  3, 20, 59, 36, 19, 90, 67, 19, 20, 96, 71, 52, 33,
       40, 39, 82,  1, 11, 92, 57, 89, 50, 23, 31, 94, 42, 99,  7, 16, 90,
       60,  2,  1, 48, 12, 69, 37, 32,  9, 99, 19, 48])


Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

In [17]:
array1_unicos = np.unique(array1)
array2_unicos = np.unique(array2)


Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

In [18]:
array3 = np.setdiff1d(array1, array2)



Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

In [19]:
array4 = np.setdiff1d(array2, array1)


Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

In [20]:
array5 = np.intersect1d(array1, array2)


¿Cuál es la relación que existe entre todos estos arrays? 

💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [21]:
print(array1.size)
print(array2.size)
print(array3.size)
print(array4.size)
print(array5.size)

80
80
26
27
27


In [22]:
print('Los dos primeros arrays son del mismo tamaño, 80. Los valores que están en array1 y no en array2 son 26, y al revés, son 27. De la misma manera, el total de elementos presentes en los dos arrays es de 27.')

Los dos primeros arrays son del mismo tamaño, 80. Los valores que están en array1 y no en array2 son 26, y al revés, son 27. De la misma manera, el total de elementos presentes en los dos arrays es de 27.
